#base_speed: 0.05
#curve_boost: 1.0
#curve_speed: 0.1
#curve_threshold: 350
#d_gain: 0.04
#detection_threshold: 80
#max_steer: 0.2
#p_gain: 0.02
#steering_threshold: 0.2
base_speed: 0.115
curve_boost: 1.0
curve_speed: 0.095
curve_threshold: 230
d_gain: 0.025
detection_threshold: 80
max_steer: 0.16
p_gain: 0.095
steering_threshold: 0.2