white_lower_h: 0
white_lower_s: 0
white_lower_v: 140
white_upper_h: 179
white_upper_s: 95
white_upper_v: 255

yellow_lower_h: 18
yellow_lower_s: 70
yellow_lower_v: 70
yellow_upper_h: 40
yellow_upper_s: 255
yellow_upper_v: 255
